export default {
  slate: {
    50: "rgba(var(--tw-colors-i-slate-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-slate-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-slate-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-slate-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-slate-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-slate-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-slate-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-slate-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-slate-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-slate-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-slate-950), <alpha-value>)",
  },
  gray: {
    50: "rgba(var(--tw-colors-i-gray-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-gray-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-gray-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-gray-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-gray-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-gray-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-gray-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-gray-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-gray-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-gray-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-gray-950), <alpha-value>)",
  },
  zinc: {
    50: "rgba(var(--tw-colors-i-zinc-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-zinc-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-zinc-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-zinc-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-zinc-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-zinc-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-zinc-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-zinc-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-zinc-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-zinc-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-zinc-950), <alpha-value>)",
  },
  neutral: {
    50: "rgba(var(--tw-colors-i-neutral-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-neutral-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-neutral-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-neutral-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-neutral-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-neutral-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-neutral-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-neutral-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-neutral-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-neutral-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-neutral-950), <alpha-value>)",
  },
  stone: {
    50: "rgba(var(--tw-colors-i-stone-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-stone-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-stone-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-stone-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-stone-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-stone-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-stone-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-stone-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-stone-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-stone-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-stone-950), <alpha-value>)",
  },
  red: {
    50: "rgba(var(--tw-colors-i-red-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-red-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-red-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-red-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-red-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-red-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-red-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-red-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-red-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-red-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-red-950), <alpha-value>)",
  },
  orange: {
    50: "rgba(var(--tw-colors-i-orange-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-orange-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-orange-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-orange-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-orange-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-orange-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-orange-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-orange-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-orange-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-orange-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-orange-950), <alpha-value>)",
  },
  amber: {
    50: "rgba(var(--tw-colors-i-amber-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-amber-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-amber-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-amber-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-amber-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-amber-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-amber-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-amber-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-amber-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-amber-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-amber-950), <alpha-value>)",
  },
  yellow: {
    50: "rgba(var(--tw-colors-i-yellow-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-yellow-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-yellow-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-yellow-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-yellow-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-yellow-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-yellow-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-yellow-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-yellow-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-yellow-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-yellow-950), <alpha-value>)",
  },
  lime: {
    50: "rgba(var(--tw-colors-i-lime-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-lime-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-lime-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-lime-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-lime-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-lime-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-lime-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-lime-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-lime-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-lime-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-lime-950), <alpha-value>)",
  },
  green: {
    50: "rgba(var(--tw-colors-i-green-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-green-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-green-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-green-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-green-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-green-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-green-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-green-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-green-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-green-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-green-950), <alpha-value>)",
  },
  emerald: {
    50: "rgba(var(--tw-colors-i-emerald-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-emerald-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-emerald-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-emerald-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-emerald-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-emerald-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-emerald-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-emerald-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-emerald-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-emerald-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-emerald-950), <alpha-value>)",
  },
  teal: {
    50: "rgba(var(--tw-colors-i-teal-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-teal-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-teal-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-teal-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-teal-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-teal-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-teal-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-teal-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-teal-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-teal-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-teal-950), <alpha-value>)",
  },
  cyan: {
    50: "rgba(var(--tw-colors-i-cyan-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-cyan-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-cyan-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-cyan-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-cyan-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-cyan-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-cyan-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-cyan-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-cyan-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-cyan-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-cyan-950), <alpha-value>)",
  },
  sky: {
    50: "rgba(var(--tw-colors-i-sky-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-sky-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-sky-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-sky-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-sky-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-sky-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-sky-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-sky-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-sky-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-sky-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-sky-950), <alpha-value>)",
  },
  blue: {
    50: "rgba(var(--tw-colors-i-blue-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-blue-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-blue-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-blue-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-blue-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-blue-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-blue-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-blue-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-blue-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-blue-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-blue-950), <alpha-value>)",
  },
  indigo: {
    50: "rgba(var(--tw-colors-i-indigo-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-indigo-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-indigo-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-indigo-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-indigo-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-indigo-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-indigo-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-indigo-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-indigo-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-indigo-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-indigo-950), <alpha-value>)",
  },
  violet: {
    50: "rgba(var(--tw-colors-i-violet-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-violet-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-violet-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-violet-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-violet-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-violet-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-violet-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-violet-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-violet-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-violet-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-violet-950), <alpha-value>)",
  },
  purple: {
    50: "rgba(var(--tw-colors-i-purple-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-purple-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-purple-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-purple-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-purple-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-purple-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-purple-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-purple-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-purple-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-purple-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-purple-950), <alpha-value>)",
  },
  fuchsia: {
    50: "rgba(var(--tw-colors-i-fuchsia-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-fuchsia-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-fuchsia-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-fuchsia-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-fuchsia-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-fuchsia-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-fuchsia-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-fuchsia-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-fuchsia-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-fuchsia-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-fuchsia-950), <alpha-value>)",
  },
  pink: {
    50: "rgba(var(--tw-colors-i-pink-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-pink-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-pink-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-pink-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-pink-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-pink-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-pink-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-pink-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-pink-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-pink-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-pink-950), <alpha-value>)",
  },
  rose: {
    50: "rgba(var(--tw-colors-i-rose-50), <alpha-value>)",
    100: "rgba(var(--tw-colors-i-rose-100), <alpha-value>)",
    200: "rgba(var(--tw-colors-i-rose-200), <alpha-value>)",
    300: "rgba(var(--tw-colors-i-rose-300), <alpha-value>)",
    400: "rgba(var(--tw-colors-i-rose-400), <alpha-value>)",
    500: "rgba(var(--tw-colors-i-rose-500), <alpha-value>)",
    600: "rgba(var(--tw-colors-i-rose-600), <alpha-value>)",
    700: "rgba(var(--tw-colors-i-rose-700), <alpha-value>)",
    800: "rgba(var(--tw-colors-i-rose-800), <alpha-value>)",
    900: "rgba(var(--tw-colors-i-rose-900), <alpha-value>)",
    950: "rgba(var(--tw-colors-i-rose-950), <alpha-value>)",
  },
  inherit: "inherit",
  current: "currentColor",
  transparent: "transparent",
  black: "rgba(var(--tw-colors-i-black), <alpha-value>)",
  white: "rgba(var(--tw-colors-i-white), <alpha-value>)",
}
