apiVersion: v1
kind: Service
metadata:
  name: xlog-lb
  namespace: crossbell
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-name: "xlog-dev"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: "slb.s1.small"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-acl-id: acl-7go649a51gt3cw7qgsvls
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-acl-status: "on"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-acl-type: black
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: xlog-caddy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: xlog-internal
  namespace: crossbell
spec:
  type: ClusterIP
  selector:
    app: xlog
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
