#!/bin/sh

### BEGIN GPTCOMMIT HOOK ###
if ! command -v gptcommit &> /dev/null
then
    echo "Not found gptcommit. Skiped."
    exit
fi
gptcommit prepare-commit-msg --commit-msg-file "$1" --commit-source "$2" --commit-sha "$3"
### END GPTCOMMIT HOOK ###
